### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by psm-2** [Yashgaur908/Twitter-clone#1]
How do you set up the code?

**Comment by TheeAndre** [comment]
@psm227 Do you need help setting up the script?

1. Create your database (MySQL or MariaDB)
2. Edit the file ```/core/database/connection.php``` with your database connection details. 
3. Import the file ```/DataBase File/tweety.sql``` into your database.
4. Upload the repo files on to your hosting. 
5. Script should work fine.
